# Automatically generated by SST
# pylint: disable=all
# ruff: noqa
from typing import Any

class Resource:
    class Api:
        type: str
        url: str
    class App:
        name: str
        stage: str
    class ClerkJwtPublicKey:
        type: str
        value: str
    class ClerkJwtSecretKey:
        type: str
        value: str
    class Connections:
        name: str
        type: str
    class JobDLQ:
        type: str
        url: str
    class JobQueue:
        type: str
        url: str
    class Jobs:
        name: str
        type: str
    class ProxyPool:
        name: str
        type: str
    class Results:
        name: str
        type: str
    class Sessions:
        name: str
        type: str
    class Templates:
        name: str
        type: str
    class Urls:
        name: str
        type: str
    class WebhookDLQ:
        type: str
        url: str
    class WebhookDeliveries:
        name: str
        type: str
    class WebhookQueue:
        type: str
        url: str
    class Webhooks:
        name: str
        type: str
    class WsApi:
        managementEndpoint: str
        type: str
        url: str

